version: '3.9'

services:
  app:
    platform: linux/amd64
    build: .
    env_file:
      - ./local.env
    depends_on:
      - elasticmq
    links:
      - elasticmq
    volumes:
      - ./:/app
  elasticmq:
    image: softwaremill/elasticmq
    hostname: presto-elasticmq
    ports:
      - "9324:9324"