version: '3.9'

services:
  app:
    platform: linux/amd64
    build: .
    env_file:
      - ./.env_file
    depends_on:
      - elasticmq
    links:
      - elasticmq
    volumes:
      - ./:/app
    ports:
      - "${PRESTO_PORT}:${PRESTO_PORT}"
    args:
      - PRESTO_PORT=${PRESTO_PORT}
  elasticmq:
    image: softwaremill/elasticmq
    hostname: presto-elasticmq
    ports:
      - "9324:9324"