version: '3.9'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        - PRESTO_PORT=${PRESTO_PORT}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - S3_ENDPOINT=${S3_ENDPOINT}
    env_file:
      - ./.env_file
    depends_on:
      elasticmq:
        condition: service_healthy
    links:
      - elasticmq
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      ROLE: server
  elasticmq:
    image: softwaremill/elasticmq
    hostname: presto-elasticmq
    ports:
      - "9324:9324"
    healthcheck:
      test: ["CMD","wget","-q","-S","-O","-","127.0.0.1:9324/?Action=ListQueues"]
      interval: 10s
      timeout: 5s
      retries: 10
  image:
    build: .
    platform: linux/amd64
    volumes:
      - "./:/app"
    env_file:
      - ./.env_file
    environment:
      ROLE: worker
      MODEL_NAME: image.Model
    depends_on:
      elasticmq:
        condition: service_healthy
  audio:
    build: .
    platform: linux/amd64
    volumes:
      - "./:/app"
    env_file:
      - ./.env_file
    environment:
      ROLE: worker
      MODEL_NAME: audio.Model
    depends_on:
      elasticmq:
        condition: service_healthy
  yake:
    build: .
    platform: linux/amd64
    volumes:
      - "./:/app"
    env_file:
      - ./.env_file
    environment: 
      ROLE: worker
      MODEL_NAME: yake_keywords.Model
    depends_on:
      elasticmq:
        condition: service_healthy
