version: '3.9'

services:
  app:
    platform: linux/amd64
    build: 
      context: .
      args:
        - PRESTO_PORT=${PRESTO_PORT}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - S3_ENDPOINT=${S3_ENDPOINT}
    env_file:
      - ./.env_file
    depends_on:
      - elasticmq
    links:
      - elasticmq
    volumes:
      - ./:/app
  elasticmq:
    image: softwaremill/elasticmq
    hostname: presto-elasticmq
    ports:
      - "9324:9324"